# Real recipes migrated from thequietledger.co/kitchen
# img: filename in images/ or None (no-photo recipes open with the lockup, no hero)

RECIPES = [
dict(slug="pie-crust", title="The Pie Crust", coll="The Basic Series",
  eyebrow="The Basic Series · No. I · The Foundation",
  dek="One bowl, cold butter, a little patience. The foundation under every pie that follows.",
  meta=["15 min + 1 hr chill","Makes two 9-inch crusts","By hand"], img=None,
  intro=["Keep everything cold — the butter, the water, your hands if you can. Cold is what makes a crust flake."],
  ingredients=[("Double crust for a 9-inch pie",[
    "2½ cups all-purpose flour","1 tsp salt","1 Tbsp sugar",
    "1 cup (2 sticks) cold unsalted butter, cubed","6–8 Tbsp ice water"])],
  method=[
    "Whisk together the flour, salt, and sugar.",
    "Cut in the cold butter until only pea-sized pieces remain.",
    "Add the ice water one tablespoon at a time, just until the dough comes together — no more.",
    "Divide into two discs.",
    "Wrap and chill at least one hour before rolling."],
  notes=["Make the crust the day before. A rested dough rolls softer, and the work of a pie feels lighter when the hardest part is already done."]),

dict(slug="basil-pesto", title="Classic Basil Pesto", coll="The Basic Series",
  eyebrow="The Basic Series · No. II · The Foundation",
  dek="High summer, made to keep — basil, toasted pine nuts, and good cheese in a single bright spoonful.",
  meta=["15 min","Makes about 1 cup","Keeps 1 week, chilled"], img=None,
  intro=["Stir it into hot pasta off the heat, never over it — pesto is meant to be warmed by the food, not cooked."],
  ingredients=[("For the pesto",[
    "2 cups packed fresh basil leaves","½ cup freshly grated Parmigiano-Reggiano",
    "¼ cup freshly grated Pecorino Romano (optional, but excellent)",
    "⅓ cup pine nuts, lightly toasted","2 garlic cloves","½ cup extra-virgin olive oil",
    "½ tsp kosher salt","Freshly ground black pepper"])],
  method=[
    "Toast the pine nuts in a dry skillet for 2–3 minutes, until fragrant. Let them cool.",
    "In a food processor, pulse the garlic and pine nuts until finely chopped.",
    "Add the basil, both cheeses, the salt, and a few grinds of pepper. Pulse several times.",
    "With the processor running, slowly drizzle in the olive oil until smooth but still slightly textured.",
    "Taste, and adjust the salt if needed."],
  notes=["Pressed flat with a thin film of olive oil over the top, it keeps its color in the fridge for a week — or freeze it in small portions for winter."]),

dict(slug="blueberry-crumb-cake", title="Blueberry Crumb Cake", coll="From the Oven",
  eyebrow="From the Oven · Summer",
  dek="Berries layered through the middle, sour cream keeping the cake tender, and big brown-sugar crumbs doing the rest.",
  meta=["Prep 25 min","Serves 8–10","9-inch springform · 350°F · 55–65 min"], img="rec-crumbcake.jpg",
  intro=["This cake is intentionally generous with both the blueberries and the crumb. Layering the berries instead of simply stirring them all into the batter gives you pockets of blueberry running through the center, while the sour cream keeps the cake underneath exceptionally tender."],
  ingredients=[
    ("Brown sugar crumb",["1¼ cups all-purpose flour","½ cup light brown sugar, packed",
      "¼ cup granulated sugar","1 tsp ground cinnamon","¼ tsp kosher salt",
      "8 Tbsp (1 stick) unsalted butter, melted","1 tsp pure vanilla extract"]),
    ("Blueberry cake",["2 cups all-purpose flour","1½ tsp baking powder","½ tsp baking soda",
      "½ tsp kosher salt","½ cup (1 stick) unsalted butter, softened","¾ cup granulated sugar",
      "2 large eggs, room temperature","2 tsp pure vanilla extract","¾ cup full-fat sour cream",
      "2 Tbsp whole milk","2 cups fresh blueberries","1 Tbsp all-purpose flour"]),
    ("Vanilla-lemon glaze",["1 cup powdered sugar","1½–2 Tbsp fresh lemon juice",
      "1 Tbsp milk or cream, as needed","½ tsp pure vanilla extract","Pinch of kosher salt"])],
  method=[
    ["<strong>Prepare the pan.</strong> Heat the oven to 350°F. Butter a 9-inch springform pan and line the bottom with parchment."],
    ["<strong>Make the crumb.</strong> Whisk together the flour, brown sugar, granulated sugar, cinnamon and salt.",
     "Add the melted butter and vanilla and stir until the mixture forms moist crumbs. Use your fingers to press some of the mixture into larger, irregular clusters. Set aside.",
     "Don’t make the crumbs too fine — the big pieces are what give the finished cake its craggy top."],
    ["<strong>Make the cake batter.</strong> Whisk together the flour, baking powder, baking soda and salt.",
     "In a separate bowl, beat the softened butter and sugar for about 3 minutes, until pale and fluffy.",
     "Add the eggs one at a time, beating well after each. Mix in the vanilla.",
     "Add the sour cream and mix until combined.",
     "Add the dry ingredients in two additions, alternating with the milk. Mix only until combined."],
    ["<strong>Prepare the blueberries.</strong> Toss the blueberries gently with 1 tablespoon flour. This helps keep them suspended throughout the cake."],
    ["<strong>Layer the cake.</strong> Spread approximately half of the batter into the prepared pan.",
     "Scatter about 1 cup of blueberries evenly over the batter.",
     "Carefully spoon the remaining batter over the berries and gently spread it to the edges. Scatter the remaining blueberries over the top, pressing them very lightly into the batter.",
     "Cover the entire surface generously with the brown-sugar crumb mixture. Use all of it."],
    ["<strong>Bake.</strong> Bake for 55–65 minutes, until the crumb is deeply golden and a toothpick inserted into the cake portion near the center comes out without wet batter.",
     "Because this is a tall, berry-heavy cake, start checking around 50 minutes but don’t pull it prematurely. If the crumb becomes dark before the center is finished, loosely tent the top with foil.",
     "Cool in the pan for about 20 minutes, then release the springform ring. Let the cake cool completely before glazing."],
    ["<strong>Make the glaze.</strong> Whisk together the powdered sugar, 1½ tablespoons lemon juice, vanilla and salt.",
     "Add additional lemon juice or a little milk or cream until you have a thick glaze that falls slowly from a spoon."],
    ["<strong>Finish.</strong> Drizzle the glaze generously back and forth over the completely cooled cake, allowing some of it to settle into the crumb topping and run slightly toward the edges.",
     "Let the glaze set for about 15 minutes before slicing."]],
  notes=["Don’t pulverize the streusel. Those big buttery brown-sugar pieces are what make this a crumb cake rather than simply a blueberry coffee cake.",
    "The little bit of lemon in the glaze isn’t there to make this a lemon cake — it just cuts through the sweetness and makes the blueberries taste brighter."]),

dict(slug="peach-galette", title="Peach Galette", coll="From the Oven",
  eyebrow="From the Oven · Summer",
  dek="Unpeeled peaches over a hidden layer of ground almonds, folded into a rustic crust and baked until properly browned.",
  meta=["Prep 25 min + chilling","Serves 6–8","Oven 400°F · 40–45 min"], img="rec-galette.jpg",
  intro=["Don’t peel the peaches. The skins soften during baking, add color, and make the galette look much more beautiful and rustic."],
  ingredients=[
    ("For the pastry",["1¼ cups all-purpose flour","1 Tbsp granulated sugar","½ tsp kosher salt",
      "½ cup (1 stick) very cold unsalted butter, cut into small cubes",
      "3–5 Tbsp ice water","1 tsp apple cider vinegar"]),
    ("For the peaches",["4–5 ripe but still firm peaches, about 1½ pounds","⅓ cup light brown sugar",
      "1 Tbsp fresh lemon juice","1 tsp pure vanilla extract","¼ tsp almond extract",
      "2 Tbsp cornstarch","¼ tsp kosher salt","Pinch of cinnamon"]),
    ("For assembling",["2 Tbsp finely ground almonds or almond flour","1 egg",
      "1 Tbsp milk or cream","Coarse sugar, for finishing",
      "1 Tbsp unsalted butter, cut into tiny pieces"])],
  method=[
    ["<strong>Make the pastry.</strong> Whisk the flour, sugar and salt together. Add the cold butter and work it into the flour with your fingertips or a pastry cutter until you have an uneven mixture with some pea-size pieces of butter remaining.",
     "Mix the vinegar with 3 tablespoons of ice water. Drizzle it over the flour mixture and gently toss. Add additional ice water, 1 tablespoon at a time, just until the dough holds together when squeezed.",
     "Form into a disk, wrap and refrigerate for at least 1 hour."],
    ["<strong>Prepare the peaches.</strong> Cut the peaches into approximately ½-inch wedges. Toss with the brown sugar, lemon juice, vanilla, almond extract, cornstarch, salt and cinnamon. Let them stand for about 10 minutes."],
    ["<strong>Roll the pastry.</strong> Heat the oven to 400°F. Roll the chilled dough on a lightly floured surface into a rustic 12–13-inch circle, about ⅛ inch thick. Transfer it to a parchment-lined baking sheet.",
     "Sprinkle the ground almonds over the center of the pastry, leaving about a 2-inch border. This little layer is important — it absorbs some of the peach juices while the galette bakes and helps keep the crust crisp."],
    ["<strong>Assemble.</strong> Arrange the peaches over the almonds, leaving most of the liquid behind in the bowl. Arrange them in concentric circles, or simply pile them naturally in the center.",
     "Fold the pastry border up and over the peaches, pleating it as you go. Dot the exposed peaches with the tablespoon of butter.",
     "Whisk the egg with the milk or cream. Brush it over the pastry and generously sprinkle the crust with coarse sugar."],
    ["<strong>Chill again.</strong> Put the assembled galette in the refrigerator for 15–20 minutes before baking. This helps the butter firm back up and gives you a flakier, better-defined crust."],
    ["<strong>Bake.</strong> Bake for 40–45 minutes, until the pastry is deeply golden and the peach juices are bubbling and thickened.",
     "Don’t pull it when the crust is merely pale gold. A galette is much better when the pastry gets properly browned and crisp.",
     "Let cool on the pan for at least 30 minutes before slicing so the peach filling has time to settle."]],
  notes=["Serve slightly warm or at room temperature. It’s excellent on its own, but for dessert I’d add vanilla bean ice cream or softly whipped cream.",
    "The two little things I’d keep in this recipe are the tiny amount of almond extract and the ground almonds underneath the peaches. Neither announces itself, but together they make the peaches taste more intensely peachy and keep that beautiful bottom crust from getting soaked.",
    "And don’t peel the peaches. The skins soften during baking, add color, and make the galette look much more beautiful and rustic."]),

dict(slug="apple-pie", title="New England Apple Pie", coll="From the Oven",
  eyebrow="From the Oven · Autumn",
  dek="Honeycrisp for sweetness, Granny Smith for backbone — and a long, slow bake until the kitchen smells like the season has finally arrived.",
  meta=["About 1 hr","One 9-inch pie","Oven 400°F, then 350°F"], img=None,
  intro=["The pie made when cold arrives and apples turn sharp. The crust is the House Pie Crust from the Basic Series, made and chilled ahead."],
  ingredients=[("For the filling",[
    "6–7 large apples (a mix of Honeycrisp and Granny Smith)","¾ cup brown sugar",
    "¼ cup granulated sugar","2 Tbsp flour","2 Tbsp cornstarch","1½ tsp cinnamon",
    "¼ tsp nutmeg","1 Tbsp lemon juice","2 Tbsp butter, for dotting","1 egg, beaten, for the wash"])],
  method=[
    "Roll out the bottom crust and settle it into the pie plate.",
    "Toss the apples with both sugars, the flour, cornstarch, cinnamon, nutmeg, and lemon juice.",
    "Fill the shell, mounding gently toward the center.",
    "Dot the top with butter.",
    "Lay on the top crust and cut a few steam vents.",
    "Brush all over with the egg wash.",
    "Bake at 400°F for 20 minutes.",
    "Reduce to 350°F and bake 35–45 minutes more, until deeply golden and bubbling at the vents."],
  notes=["If the edges brown before the center sets, lay a loose ring of foil over them.","Cool overnight before slicing."]),

dict(slug="cherry-pie", title="The Cherry Pie That Started It All", coll="From the Oven",
  eyebrow="From the Oven · Summer",
  dek="Tart cherries, a whisper of almond, an afternoon with nowhere else to be.",
  meta=["1 hr + cooling","One 9-inch pie","Oven 400°F, then 350°F"], img=None,
  intro=["It is not a difficult pie, only an unhurried one — the kind of thing worth doing on a quiet day. The first pie photographed for the Ledger."],
  ingredients=[("For the filling",[
    "5 cups tart cherries (fresh or frozen)","¾ cup sugar (up to 1 cup for a sweeter pie)",
    "3 Tbsp cornstarch","1 Tbsp lemon juice","½ tsp almond extract",
    "1 Tbsp butter, for dotting","1 egg, beaten, for the wash"]),
    ("The base",["House Pie Crust, made and chilled ahead"])],
  method=[
    "Roll out the bottom crust and settle it into the pie dish.",
    "Combine the cherries, sugar, cornstarch, lemon juice, and almond extract.",
    "Pour the filling into the crust.",
    "Dot the top with butter.",
    "Roll out the top crust, lay it over the filling, trim, and crimp the edges.",
    "Cut a few steam vents, then brush with the egg wash.",
    "Bake at 400°F for 20 minutes.",
    "Reduce to 350°F and bake 35–40 minutes more, until the juices bubble thickly through the vents."],
  notes=["Let it cool completely before slicing. The almond is quiet but it’s the whole secret — don’t leave it out."]),

dict(slug="pear-tarte-tatin", title="Pear Tarte Tatin", coll="From the Oven",
  eyebrow="From the Oven · Late Autumn",
  dek="The quiet showpiece — pears turned in dark caramel, then flipped to the light.",
  meta=["About 45 min","One skillet tart","Oven 425°F"], img=None,
  intro=["Pears turned in dark caramel, capped with puff pastry, then flipped to reveal what the heat has been doing all along."],
  ingredients=[("For the tart",[
    "5–6 ripe but firm pears, peeled, cored, and thinly sliced","½ cup unsalted butter",
    "¾ cup sugar","1 sheet puff pastry","Pinch of salt"])],
  method=[
    "Heat the oven to 425°F.",
    "In an oven-safe skillet, melt the butter and sugar together.",
    "Cook, without stirring much, until a deep amber caramel forms.",
    "Arrange the pear slices in tight, overlapping rings in the caramel.",
    "Cook a few minutes, letting the slices soften and take on the color.",
    "Lay the puff pastry over the pears and tuck the edges down inside the pan.",
    "Bake 25–30 minutes, until the pastry is deeply golden.",
    "Cool 10 minutes — no longer, or it will stick.",
    "Set a plate over the skillet and, carefully, invert."],
  notes=["The inversion is the only moment that asks for confidence. A short rest, a steady plate, one decisive turn."]),

dict(slug="chocolate-chip-cookies", title="Bakery-Style Chocolate Chip Cookies", coll="From the Oven",
  eyebrow="From the Oven · Every Season",
  dek="Brown butter, two kinds of chocolate, and a dough that rests a day in the refrigerator. The one the house asks for by name.",
  meta=["Chill 2–24 hrs","18 large cookies","Oven 375°F · 11–13 min"], img=None,
  intro=["The dough keeps refrigerated for three days, or can be frozen in scooped mounds and baked directly from frozen — add a minute or two."],
  ingredients=[
    ("The brown butter",["1 cup (226 g) unsalted butter"]),
    ("The dry",["2 cups bread flour","1 cup all-purpose flour","1 tsp baking soda",
      "1 tsp baking powder","1 tsp cornstarch","1 tsp kosher salt"]),
    ("The wet",["1¼ cups dark brown sugar","½ cup granulated sugar","1 large egg",
      "1 egg yolk","2 tsp vanilla extract"]),
    ("The chocolate",["10 oz chopped dark or bittersweet chocolate",
      "4 oz semisweet chocolate chips, or chopped semisweet chocolate",
      "Flaky sea salt, for finishing (optional)"])],
  method=[
    "Brown the butter in a light-colored pan over medium heat, swirling occasionally, until the foam settles and the solids turn amber with a nutty aroma. Pour into a large bowl with all the browned bits; cool until just warm.",
    "Whisk together the bread flour, all-purpose flour, baking soda, baking powder, cornstarch, and kosher salt.",
    "Mix the warm brown butter with both sugars until smooth.",
    "Beat in the egg, yolk, and vanilla.",
    "Fold in the dry ingredients until no flour streaks remain.",
    "Fold in the chocolate.",
    "Cover and chill the dough at least 2 hours — 24 hours is better.",
    "Heat the oven to 375°F. Scoop the dough into 3–4 tablespoon mounds on lined sheets, well spaced.",
    "Bake 11–13 minutes, until the edges are golden and the centers look slightly underdone. Top with flaky salt while warm if you like. Cool on the pan a full 10 minutes."],
  notes=["The rest in the refrigerator is not optional — it is what makes them bakery-style."]),

dict(slug="white-chocolate-macadamia", title="White Chocolate Macadamia Cookies", coll="From the Oven",
  eyebrow="From the Oven · Every Season",
  dek="Toasted macadamias, white chocolate chopped from a good bar, and a whisper of almond. The quiet one that goes first.",
  meta=["Chill 2 hrs+","18–20 large cookies","Oven 375°F · 12 min"], img=None,
  intro=["Toasting the nuts takes eight minutes and no skill at all."],
  ingredients=[
    ("The dry",["2¼ cups (270 g) bread flour","½ cup (60 g) all-purpose flour",
      "1 tsp baking soda","1 tsp cornstarch","¾ tsp kosher salt"]),
    ("The wet",["1 cup (227 g) unsalted butter, softened","1 cup (200 g) light brown sugar, packed",
      "½ cup (100 g) granulated sugar","1 large egg","1 egg yolk","2 tsp vanilla extract",
      "½ tsp almond extract (optional)"]),
    ("The folding in",["1½ cups toasted macadamia nuts, roughly chopped",
      "1½ cups high-quality white chocolate, chopped","Flaky sea salt, for finishing (optional)"])],
  method=[
    "Toast the macadamias at 325°F for 8–10 minutes, until fragrant and golden; cool completely.",
    "Whisk together the dry ingredients.",
    "Cream the butter with both sugars for 3–4 minutes, until light and fluffy.",
    "Beat in the egg, yolk, vanilla, and almond extract if using.",
    "Mix in the dry ingredients until just combined.",
    "Fold in the white chocolate and toasted macadamias.",
    "Cover and chill at least 2 hours; overnight is better.",
    "Heat the oven to 375°F; scoop the dough in 3-tablespoon portions onto parchment, well spaced.",
    "Bake 11–13 minutes, until the edges are lightly golden and the centers look slightly underdone. Finish with sea salt while warm if you like; cool on the pan 10 minutes before moving."],
  notes=["Chop the white chocolate from a bar — it melts into the crumb in a way chips never do."]),

dict(slug="raspberry-white-chocolate-cookies", title="Raspberry White Chocolate Cookies", coll="From the Oven",
  eyebrow="From the Oven · Every Season",
  dek="Freeze-dried raspberries folded in whole, so the flecks stay bright pink through the oven. Crisp at the edge, soft in the middle.",
  meta=["Chill 45–60 min","About 24 cookies","Oven 350°F · 10–12 min"], img="rec-raspberry.jpg",
  intro=["Freeze-dried raspberries, not fresh — fresh fruit turns the dough wet and grey. The freeze-dried ones keep their color and their sharpness."],
  ingredients=[
    ("The wet",["¾ cup unsalted butter, softened","⅔ cup granulated sugar",
      "⅓ cup packed brown sugar","1 large egg","1 large egg yolk","1½ tsp pure vanilla extract"]),
    ("The dry",["2¼ cups all-purpose flour","¾ tsp baking soda","½ tsp fine sea salt"]),
    ("The folding in",["1 cup good-quality white chocolate, chopped",
      "1 cup freeze-dried raspberries, very lightly crushed"])],
  method=[
    "Beat the softened butter with both sugars until light and creamy, about 2–3 minutes.",
    "Beat in the egg, yolk, and vanilla until smooth.",
    "Stir in the flour, baking soda, and salt just until combined. Do not overmix.",
    "Gently fold in most of the white chocolate and raspberries, reserving a small handful for the tops. Fold only until evenly distributed.",
    "Cover and refrigerate the dough 45–60 minutes.",
    "Heat the oven to 350°F and line baking sheets with parchment. Scoop the dough into 1½-tablespoon balls, two inches apart. Press the reserved pieces into the tops.",
    "Bake 10–12 minutes, until the edges are set and golden while the centers remain soft. Cool on the sheet 5 minutes, then transfer to a rack."],
  notes=["The dough freezes well in balls — add a minute or two to the bake time from frozen."]),

dict(slug="vanilla-bean-sugar-cookies", title="Vanilla Bean Sugar Cookies", coll="From the Oven",
  eyebrow="From the Oven · Every Season",
  dek="Real vanilla bean in both the dough and the glaze, tops left pale on purpose, and a make-ahead plan that holds for a party.",
  meta=["Chill 45 min","About 24 cookies","Oven 350°F · 10–13 min"], img="rec-vanilla.jpg",
  intro=["Pale on top, soft in the middle, finished with a thin vanilla glaze."],
  ingredients=[
    ("The dough",["1 cup unsalted butter, softened","1 cup granulated sugar","1 large egg",
      "1 large egg yolk","1 Tbsp vanilla bean paste","¼ tsp pure almond extract",
      "2¾ cups all-purpose flour","¾ tsp baking powder","½ tsp fine sea salt"]),
    ("The glaze",["1½ cups confectioners’ sugar","2–3 Tbsp whole milk or heavy cream",
      "1 Tbsp unsalted butter, melted and cooled slightly","½ tsp vanilla bean paste",
      "Small pinch fine sea salt"])],
  method=[
    "Beat the softened butter and sugar until pale, creamy, and slightly fluffy, about 2–3 minutes.",
    "Beat in the egg, yolk, vanilla bean paste, and almond extract until smooth, scraping the bowl as needed.",
    "Whisk the flour, baking powder, and salt separately; mix into the butter on low speed until a soft dough forms. Do not overmix.",
    "Cover and refrigerate the dough 45 minutes.",
    "Scoop into roughly 1½-tablespoon portions, roll into smooth balls, and flatten each very slightly with your palm.",
    "Heat the oven to 350°F and arrange the dough two inches apart on parchment-lined sheets.",
    "Bake 10–13 minutes, until the edges are set and the bottoms are very lightly golden, keeping the tops pale. Cool completely.",
    "Whisk the glaze ingredients until smooth, adding milk only as needed.",
    "Spoon or dip the cooled cookies in a thin layer of glaze. Leave uncovered 45–60 minutes until fully set before stacking."],
  notes=["Freeze the shaped, unbaked cookies on a tray, then bag them — they keep two months and bake from frozen with a minute or two added."]),

dict(slug="brown-butter-snickerdoodles", title="Brown Butter Snickerdoodles", coll="From the Oven",
  eyebrow="From the Oven · Every Season",
  dek="The old cinnamon cookie with browned butter underneath it — nutty and deep, with crisp edges and a soft center.",
  meta=["Chill 45 min","About 24 cookies","Oven 350°F · 9–11 min"], img="rec-snick.jpg",
  intro=["The old cinnamon cookie, made with butter that spent seven minutes turning into something else."],
  ingredients=[
    ("The dough",["1 cup (2 sticks) unsalted butter","1½ cups granulated sugar","2 large eggs",
      "1 large egg yolk","1 tsp pure vanilla extract","2¾ cups all-purpose flour",
      "2 tsp cream of tartar","1 tsp baking soda","½ tsp fine sea salt"]),
    ("The rolling sugar",["¼ cup granulated sugar","1 Tbsp ground cinnamon"])],
  method=[
    "Melt the butter in a light-colored saucepan over medium heat, swirling often, until the milk solids are deep golden and smell nutty, 5–7 minutes. Pour into a mixing bowl, scraping in the browned bits, and cool 15–20 minutes.",
    "Whisk the sugar into the cooled brown butter until smooth. Add the eggs, egg yolk, and vanilla; whisk until glossy.",
    "Stir in the flour, cream of tartar, baking soda, and salt until no dry streaks remain. Do not overmix.",
    "Cover and refrigerate at least 45 minutes.",
    "Heat the oven to 350°F and line baking sheets with parchment. Stir the rolling sugar and cinnamon together. Scoop the dough into 1½-tablespoon balls, roll generously in cinnamon sugar, and set two inches apart.",
    "Bake 9–11 minutes, until the edges are set and lightly golden while the centers still look slightly soft.",
    "Rest on the baking sheet 5 minutes, then move to a wire rack."],
  notes=["To freeze: chill the dough first, scoop and roll in cinnamon sugar, freeze on a tray until solid, then bag. Bake from frozen at 350°F for 10–13 minutes, pulling them while the centers still look underdone."]),

dict(slug="lemon-sugar-cookies", title="Soft Lemon Sugar Cookies", coll="From the Oven",
  eyebrow="From the Oven · Every Season",
  dek="Zest rubbed into the sugar by hand, soft centers left pale, and a thin lemon glaze. Better on the second day than the first.",
  meta=["Chill 30–45 min","About 24 cookies","Oven 350°F · 9–11 min"], img="rec-lemon.jpg",
  intro=["Rubbing the zest into the sugar by hand takes thirty seconds and is where all the flavor lives."],
  ingredients=[
    ("The dough",["2¾ cups (345 g) all-purpose flour","½ tsp baking soda","½ tsp baking powder",
      "½ tsp fine salt","¾ cup (170 g) unsalted butter, softened","1¼ cups (250 g) granulated sugar",
      "Zest of 2 large lemons","1 large egg plus 1 egg yolk, room temperature",
      "2 Tbsp fresh lemon juice","1 tsp vanilla extract","½ tsp lemon extract"]),
    ("The lemon glaze",["1½ cups (180 g) powdered sugar","2–3 Tbsp fresh lemon juice",
      "½ tsp vanilla extract","Tiny pinch of salt","Finely grated lemon zest, optional"])],
  method=[
    "Heat the oven to 350°F and line baking sheets with parchment.",
    "Rub the lemon zest into the granulated sugar for about 30 seconds, until fragrant and slightly damp.",
    "Cream the lemon sugar and butter 2–3 minutes, until light. Beat in the egg and yolk, then the lemon juice, vanilla, and lemon extract.",
    "Whisk the flour, baking soda, baking powder, and salt in a separate bowl. Mix into the butter mixture just until combined; do not overmix.",
    "Chill the dough 30–45 minutes.",
    "Portion into 40–45 g balls, arrange two inches apart, and flatten the tops slightly.",
    "Bake 9–11 minutes, until the edges are set but the centers still look soft.",
    "Rest on the baking sheet 5 minutes, then transfer to a rack and cool completely.",
    "Whisk the glaze ingredients until thick but drizzleable. Drizzle over the completely cooled cookies; add zest if you like.",
    "Let the glaze set 1–2 hours before storing."],
  notes=["Store at room temperature with parchment between the layers — do not refrigerate. They stay soft, and the flavor deepens over two days.","Skip fresh lemon slices as decoration when storing; they release moisture."]),
]

# Suppers — collection entries (full recipe pages still to be written/migrated)
SUPPERS = [
  dict(title="Turkey Potpie", desc="Peas, carrots, corn, and mushrooms with turkey and gravy beneath a homemade double crust. Comfort without heaviness."),
  dict(title="Chicken Potpie", desc="The everyday version — chicken and gravy with peas, carrots, corn, green beans, and mushrooms under a double crust. Rarely leaves leftovers."),
  dict(title="Italian Antipasto Pasta Salad", desc="Salami, pepperoni, fresh mozzarella, olives, and Parmesan tossed with pasta in a red-wine vinaigrette. Served cold."),
  dict(title="Balsamic Meatloaf", desc="A tender, milk-soft loaf under a sticky glaze of balsamic, brown sugar, and ketchup."),
  dict(title="Pan-Seared Salmon with Garlic Butter", desc="Fifteen minutes — salt, pepper, a garlic sear, and a finish of foaming thyme butter and lemon."),
  dict(title="Cedar-Plank Salmon with Fresh Thyme", desc="The plank soaks an hour, the honey-Dijon glaze goes on, and the cedar smokes gently while it grills.", img="s1.jpg"),
]

# The Edit — real products and affiliate links from shesthegoose.com/finds
EDIT = [
dict(key="table", title="The Table", img="edit-table.jpg",
  cap="The long table in October — chargers, tapers, and the runner built that morning.",
  body="What the table is actually set with. Five things, all of them in the photographs on this site.",
  items=[
    ("Gold Petal Charger Plates","The piece that anchors every setting without competing with what’s on top.","https://amzn.to/3PN0MTr"),
    ("Vegan Leather Placemats","Round, warm-toned, and effortless beneath anything.","https://amzn.to/4bksfV5"),
    ("Carved Mango Wood Bowl","Lemons, fruit, or left empty — this bowl is on my table year round.","https://amzn.to/4bTMUPV"),
    ("Hyoola Taper Candles","Tall, clean, unscented. The candles I keep restocking.","https://amzn.to/4scB3lK"),
    ("Silk Tulip Arrangement","Mixed with fresh stems, no one knows the difference.","https://amzn.to/4rtHvE1")]),
dict(key="kitchen", title="The Kitchen", img="edit-kitchen.jpg",
  cap="The Dinamica and the dark roast &mdash; two entries on this list, photographed where they live.",
  body="The tools that cook everything photographed here. Eight things, all in daily use.",
  items=[
    ("HexClad 5-Qt Hybrid Dutch Oven","Half the weight of cast iron. PFAS-free, oven safe to 900°F.","https://amzn.to/4uoyMFP"),
    ("HexClad Damascus Steel Knife Set","67 layers of Japanese Damascus steel.","https://amzn.to/4ru2vKA"),
    ("HexClad Hybrid Pot Set","Every size you actually need, none you don’t.","https://amzn.to/4sE3icR"),
    ("HexClad Hybrid Frying Pan","The pan I use every single day. Sears like stainless, releases like nonstick.","https://amzn.to/4sHNwhh"),
    ("DeLonghi Dinamica Espresso Machine","Bean to cup in under a minute.","https://amzn.to/46YajNq"),
    ("Fabula Dark Roast Coffee","Organic, mold-free, single-origin.","https://amzn.to/4b8Yu9B"),
    ("Ribbed Ceramic Coffee Mugs","Heavy in the hand, smooth on the lip.","https://amzn.to/412i1m7"),
    ("Breville Electric Kettle","Temperature control for tea, pour-over, or anything that deserves precision.","https://amzn.to/47LMfh1")]),
dict(key="home", title="The Home", img="edit-home.jpg",
  cap="The porch in July. Everything here has been left outdoors since May.",
  body="What makes the house feel like someone lives in it. Five things that have earned their place.",
  items=[
    ("Capri Blue Volcano Candle","The scent that has lived in this house for years.","https://amzn.to/47LHbsZ"),
    ("Creative Co-op Ceramic Birds","Quiet and beautiful — the kind of thing that makes a space feel collected.","https://amzn.to/4s6rYeg"),
    ("Cozecube Knit Throw","Soft without being precious, warm without being heavy.","https://amzn.to/47JCboI"),
    ("The Art of Home — Shea McGee","Beautiful to look at, genuinely useful to read.","https://amzn.to/4bwnQNP"),
    ("Peonies — Botanical Art Book","One of the most beautiful books I own.","https://amzn.to/47NE2ZI")]),
]
