# The Quiet Letters — real published text, migrated from thequietledger.co
# Each: no, slug, title, season, epigraph, source, body (list of paragraphs), signed

LETTERS = [
dict(no=1, slug="letter-01", title="The Hour Before Anyone Else Wakes", season="Winter",
epigraph="In the morning, Lord, you hear my voice; in the morning I lay my requests before you and wait expectantly.", source="Psalm 5:3",
excerpt="There is a particular quality to the house before anyone else is in it. Not silence exactly — a kind of held breath. The world paused mid-sentence.",
signed=False, body=[
"There is a particular quality to the house before anyone else is in it.",
"Not silence exactly — the furnace ticks, a faucet drips somewhere, the dog shifts on the floor — but a kind of held breath. The world paused mid-sentence. You move through it carefully, the way you’d move through a room where someone is sleeping.",
"I started waking early by accident. A phase of insomnia that eventually became a habit, and then something I chose. Now I protect it the way I protect very few things.",
"The ritual is small. Coffee, always. The same mug, the one with the chip on the handle that I’ve never replaced. I don’t turn on many lights. There’s something about the dark that I don’t want to break too quickly — it feels like a gift I didn’t earn and might lose if I’m careless.",
"I sit at the kitchen table or the window seat, depending on the season. In winter, it’s the window — the streetlamp catches the snow, or the bare branches, or the frost on the glass, and it’s enough. Just that.",
"People talk about morning routines as productivity tools. Things to optimize. I understand the impulse but I’ve come to think it’s wrong. The hour before anyone else wakes isn’t for getting ahead. It’s for remembering who you are before the day starts asking things of you.",
"There’s no output. Nothing to show for it.",
"That, I’ve decided, is precisely the point.",
"The coffee goes cold. The sky shifts from black to gray to the particular blue that means morning is really arriving now. Somewhere upstairs, something stirs.",
"I finish the cup. I start the day."]),

dict(no=2, slug="letter-02", title="A January Kitchen", season="Winter",
epigraph="The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning.", source="Lamentations 3:22–23",
excerpt="The decorations come down on the first of January, or close to it. A January kitchen is an honest one.",
signed=False, body=[
"The decorations come down on the first of January, or close to it.",
"Not out of impatience — I love Christmas, the candles and the clutter of it, the way the house feels briefly like somewhere else. But there is a moment, right around New Year’s, when I’m ready to have it back. The ordinary version. The one that’s mine year-round.",
"I start in the kitchen.",
"The wreath comes off the cabinet. The red linen goes back in the drawer. The little ceramic trees from the windowsill get wrapped in tissue and returned to their box. And then I stand there in the middle of it all and just look.",
"A January kitchen is an honest one.",
"The refrigerator after the holidays tells you everything. Half a wheel of something expensive. Leftover pie that no one will finish. Condiments that came out for a party and haven’t found their way back. I take stock slowly, the way you’d read a letter you’ve been putting off. Not with dread — with attention.",
"This is the part I’ve come to love.",
"There’s something clarifying about a stripped-down pantry and a clean shelf. January asks you to start with what you have. To make broth from the bones in the freezer, soup from the root vegetables that got pushed to the back. To eat simply for a while, after all that abundance. The body wants it. The kitchen seems to want it too.",
"I reset the counters. Put back only what belongs there — the cutting board, the wooden spoon, the olive oil. Everything else finds a drawer or a cabinet or a reason to leave entirely.",
"By mid-morning, the kitchen looks like itself again.",
"A new year doesn’t announce itself with fanfare in this house. It arrives quietly, in the form of a clean counter and a pot of something plain and nourishing on the stove. The holiday is over. The ordinary life — the good one — begins again.",
"The kitchen is ready."]),

dict(no=3, slug="letter-03", title="Snow Days and the Permission to Rest", season="Winter",
epigraph="He says to the snow, ‘Fall on the earth.’", source="Job 37:6",
excerpt="There is no negotiating with a snow day. It arrives without asking, shuts things down without apology, and rearranges whatever you had planned.",
signed=False, body=[
"There is no negotiating with a snow day.",
"It arrives without asking, shuts things down without apology, and rearranges whatever you had planned into something else entirely. I used to resist this. Now I’ve learned to read it for what it is — an instruction. A small directive from winter to stop.",
"I listen better than I used to.",
"The house is quiet in a way it only gets in winter. My stepchildren are grown and living their own lives now, which means snow days have changed. There is no one home from school, no cocoa to make for anyone else, no boots left in the hallway. Just the house and me and the particular silence that settles in when the world outside goes white.",
"I turn on the fireplace.",
"The room changes when the fire is lit. The air softens. The light shifts. I have sat beside it on gray February afternoons and felt something loosen in my chest that I didn’t realize was held.",
"The snow keeps falling. I don’t check the time.",
"I make something slow for lunch. I read. I sit with my coffee longer than necessary and watch the yard disappear under white. The fireplace does its quiet work beside me and I think — not for the first time — that happiness does not always arrive as an event.",
"Sometimes it arrives as a morning with nowhere to be, a fire already lit, and snow that shows no sign of stopping.",
"These are the days I want to remember.",
"The fire keeps burning.",
"The snow keeps falling."]),

dict(no=4, slug="letter-04", title="On Reading in Bed", season="Winter",
epigraph="When you lie down, you will not be afraid; when you lie down, your sleep will be sweet.", source="Proverbs 3:24",
excerpt="There are three books on my nightstand right now. They’ve been there long enough to feel permanent — the way certain things in a house stop being objects and quietly become fixtures.",
signed=False, body=[
"There are three books on my nightstand right now: the Bible, <em>Jesus Calling,</em> and a book called <em>Gentle and Lowly</em> — about the heart of Jesus, and how he really feels about us.",
"They’ve been there long enough to feel permanent, the way certain things in a house stop being objects and quietly become fixtures. I don’t move them. I don’t replace them. I simply reach for them.",
"This is the last ritual of the day.",
"Not a screen. Not a podcast. Not the restless pull of something that will follow me into sleep.",
"Just the lamp on the nightstand, the pillow adjusted, the covers pulled up, and the quiet that settles once the house has finally gone still.",
"I’ve tried reading other things at night. Novels, mostly. Sometimes nonfiction. There is a time for those — but not here, not at the end of the day.",
"What I want at night is not entertainment or information.",
"What I want is stillness.",
"Something that slows the mind rather than engages it.",
"Something that reminds me, after a full day of doing and deciding and moving, that I am held.",
"That is what these books do.",
"<em>Jesus Calling</em> is a daily devotional written as if Christ himself is speaking directly to you. Just a page, sometimes less. I’ve read entries that felt so precisely timed it was hard to believe they weren’t written for that exact evening.",
"<em>Gentle and Lowly</em> is a slower read. Some nights I read only a paragraph before stopping, because something in it needs room to settle. It’s a book about the character of Christ — not his power or his teaching, but his tenderness.",
"The way he meets people.",
"The way he meets me.",
"The Bible comes last, or sometimes first. Often a psalm. Something small enough to hold in my mind as sleep arrives.",
"I don’t always make it through the page.",
"That’s all right.",
"There is something I’ve come to love about falling asleep mid-sentence in a book like this — as if the words continue working quietly while the rest of me rests.",
"The lamp goes off.",
"The books remain on the nightstand.",
"Waiting for tomorrow night."]),

dict(no=5, slug="letter-05", title="February, Which Is Harder Than It Looks", season="Winter",
epigraph="He gives strength to the weary and increases the power of the weak.", source="Isaiah 40:29",
excerpt="Nobody warns you about February. December has its lights and its reason for being. January has the clean slate. But February arrives with none of it.",
signed=False, body=[
"Nobody warns you about February.",
"December has its lights and its reason for being. January has the clean slate, the reset, the sense of something beginning. But February arrives with none of it. The holidays are gone. The novelty of snow has faded. Spring still feels far away — not just in the calendar but in the body, in the bones.",
"It is the month when winter feels heaviest.",
"The days are slightly longer now. Technically. The light lingers a few minutes past where it was in December, and if you are paying close attention you might notice it — the way the sky holds a thin blue at five o’clock instead of going straight to dark. But it is not enough to feel like progress.",
"Not yet.",
"What remains in February, once the beauty of the season has worn thin, is endurance.",
"There is no other word for it. You put on the coat again. You go out into the cold again. You make the soup, light the candle, wait. Not with despair — there is nothing dramatic about February. It asks for something quieter than that. A steady, unhurried willingness to remain.",
"I have come to think this is its own practice.",
"The same way a long marriage asks you to love on the ordinary days, not just the luminous ones. The same way faith asks you to show up when nothing feels particularly holy. February is the month that asks: can you stay present when there is nothing to celebrate, nothing arriving, nothing yet to see?",
"Most years, I can.",
"Some years it takes until the last week of the month before I remember that March is coming. That the ground is doing something underneath all that cold and gray, even when I cannot see it. That endurance, practiced long enough, becomes its own quiet form of hope.",
"February always ends.",
"It just takes longer than it should.",
"Nobody warns you about that part."]),

dict(no=6, slug="letter-06", title="What Candles Are Actually For", season="Winter",
epigraph="Your word is a lamp to my feet and a light to my path.", source="Psalm 119:105",
excerpt="I light a candle almost every day. Not for a special occasion. Just because the day goes better with one.",
signed=False, body=[
"I light a candle almost every day.",
"Not for a special occasion. Not because someone is coming over or because the table needs setting. Just because the day goes better with one. The smell of it, the small steady flame, the way the light in the room shifts from something flat and functional to something else entirely — warmer, slower, more like a place worth being in.",
"There are easier ways to make a room bright.",
"A lamp is more practical. A switch is faster. Electricity asks almost nothing of you. A candle, on the other hand, requires a small decision. You strike the match. You wait for the wick to catch. You watch the flame steady itself before setting the match aside.",
"For something so simple, it is surprisingly deliberate.",
"This is not decoration. It never was.",
"There is a difference between a room with a candle burning and a room without one, and the difference is not aesthetic. It is something closer to permission. The candle says: this moment is worth marking. Not a holiday, not an achievement — just this ordinary Tuesday, this cup of coffee, this particular gray afternoon.",
"Worth the small ceremony of a flame.",
"I think we underestimate what candles are actually doing.",
"They are not ambiance. They are not a trend or a season or a style. They are one of the oldest human instincts — to make light against the dark, to gather around warmth, to signal that something is being tended.",
"A candle on a kitchen counter in the middle of winter is a quiet act of defiance against the cold and the gray.",
"It says: something is alive in here.",
"The smell matters too.",
"A good candle changes the character of a room the way music does — without announcement, without effort, simply by being present. I have candles for different seasons, different moods, different hours of the day. The heavy warm ones for winter evenings. The lighter ones for mornings when I want the house to feel like it’s waking up rather than simply turning on.",
"People sometimes ask if it’s worth it. The cost of a good candle, the small ritual of lighting one.",
"I always think: worth it compared to what?",
"A candle lit in the middle of an ordinary day is a small declaration. That the ordinary day deserves something. That you are present in it. That the hour you are sitting in right now — tired or quiet or simply going about your life — is worth the light.",
"That has always been what candles are actually for."]),

dict(no=7, slug="letter-07", title="The Pot on the Stove", season="Winter",
epigraph="She watches over the affairs of her household and does not eat the bread of idleness.", source="Proverbs 31:27",
excerpt="There is a particular kindness in a pot of soup. It does not demand attention. It asks only that you begin.",
signed=False, body=[
"There is a particular kindness in a pot of soup.",
"It does not demand attention. It does not require precision or perfect timing. It asks only that you begin. A little onion in the bottom of the pot, something simmering slowly, the quiet promise that by evening the kitchen will smell the way a kitchen should — warm, deep, and like something worth coming home to.",
"I start making soup when the season turns.",
"Not because I decide to, exactly. It happens the way most good things in a house happen — gradually, then all at once. One cool morning I reach for the heavy pot instead of the skillet, and that is how I know the year has shifted. The pot goes on the stove. Something begins.",
"Soup is patient in a way that other cooking is not.",
"A roast needs watching. A sauce demands stirring. But soup asks almost nothing. Only that you stay nearby. That you tend it occasionally. That you trust slow heat to do its quiet work while the afternoon moves through the windows.",
"Before long the house fills with the smell of it.",
"That smell is half the meal.",
"I make different soups through the season — some hearty enough to be dinner on their own, others light enough to sit beside a loaf of bread and still make the table feel generous. What they share is time. Soup that has been allowed to take its time always tastes different from soup that was hurried.",
"The cold months are the right time for it.",
"The days grow shorter. The impulse to be outside fades. The house becomes the center of things again for a while, and soup is one of the ways I make it feel like a place worth staying.",
"The pot on the stove.",
"Steam against the window.",
"The smell that greets whoever comes through the door.",
"That is what I am making when I make soup.",
"Not just dinner.",
"Something that says:",
"you are expected here, and something warm is waiting."]),

dict(no=8, slug="letter-08", title="The Warmth of a Known Routine", season="Winter",
epigraph="Commit your works to the Lord, and your plans will be established.", source="Proverbs 16:3",
excerpt="There is a version of repetition that feels like failure. And then there is the other kind — the kind where the sameness is a sign that something is being held.",
signed=False, body=[
"There is a version of repetition that feels like failure.",
"The same day again.",
"The same tasks, the same order.",
"The same cup in the same hand.",
"And then there is the other kind.",
"The kind that feels less like a rut and more like a foundation. The kind where the sameness is not a sign that nothing is happening, but a sign that something is being held.",
"A known routine is a form of care.",
"Not just for the people and animals who depend on it — the dogs who wait by the door, the husband whose lunch appears on the counter without being asked for — but for yourself.",
"There is something in the body that settles when the morning goes the way mornings go.",
"The coffee made the same way.",
"The familiar path through the kitchen.",
"The sequence of small tasks unfolding in their quiet order.",
"The hands already know what to do, and because of that the mind is free to be elsewhere.",
"This is not monotony.",
"Monotony is emptiness repeating.",
"A known routine is something different. It is a life that has slowly been shaped into something that works. Something steady. Something reliable.",
"The repetition is not the problem.",
"It is the point.",
"I have heard people say they want more spontaneity. More variety. More of the unexpected.",
"And I understand that.",
"But I have come to believe that spontaneity means more when it arrives inside a structure. That the unexpected guest is more welcome in a house that is already in order. That a day that breaks from routine is only a gift if you have a routine to break from.",
"The same mug.",
"The same chair.",
"The same window with the same light falling through it each morning.",
"These are not small things.",
"They are the quiet architecture of a life.",
"The things you have chosen — consciously or not — to return to each day because they work.",
"Because they hold the day steady before it has the chance to ask anything of you.",
"That is the warmth of a known routine."]),

dict(no=9, slug="letter-09", title="Walking in Cold Air", season="Winter",
epigraph="He makes me lie down in green pastures. He leads me beside still waters. He restores my soul.", source="Psalm 23:2–3",
excerpt="There is something a walk gives you that nothing else does. A kind of restoration. I walk by the Sound.",
signed=False, body=[
"There is something a walk gives you that nothing else does.",
"Not exercise, though that is part of it. Not fresh air, though you come back with your lungs feeling scrubbed and your cheeks carrying the cold long after you’ve stepped inside.",
"It is something harder to name than either of those things.",
"A kind of restoration.",
"I walk by the Sound.",
"That kind of beauty asks something of you.",
"It asks you to be present. To stop thinking about what comes next and simply stand at the edge of something vast and let it be vast.",
"There is a particular peace that arrives in those moments — not the peace of nothing happening, but the peace of something so much larger than yourself that your own worries briefly lose their grip.",
"Nothing has changed.",
"And still, something has.",
"I come back from every walk with more than I left with.",
"More clarity. More steadiness.",
"More of whatever it is that gets worn down by staying inside too long.",
"The cold does not take from you — it gives.",
"It sharpens something. It returns something.",
"The air is cold.",
"The water is still.",
"That is enough."]),

dict(no=10, slug="letter-10", title="What Comes Back", season="Spring",
epigraph="For, lo, the winter is past, the rain is over and gone; the flowers appear on the earth; the time of the singing of birds is come.", source="Song of Solomon 2:11–12",
excerpt="The ground is still cold. I kneel down to it anyway.",
signed=True, body=[
"The ground is still cold. I kneel down to it anyway.",
"It is the first afternoon warm enough to be outside without a coat, and I have come to the bed below the stone wall, where the hyacinths are breaking through. They came up before anything else — pale and tightly furled, the whole season pressed into their narrow bodies.",
"I had nearly forgotten them.",
"That is the strange mercy of what gets planted in October. Something pressed into cold ground, when nothing felt hopeful, will come back without being asked. The work was done before the freeze. The hands that did it were tired. And here is the proof, six months later, lifted into the light.",
"The shovel goes in. The earth turns darker than I expected, already warming beneath the surface.",
"I press the new bulbs into the soil and firm the ground over them. My ring is muddy. My knees ache. I stay anyway.",
"We do not always know what we are tending when we tend it.",
"This is the work of spring. Not the bloom, not yet. The kneeling. The bending close. The remembering of what was planted."]),

dict(no=11, slug="letter-11", title="A Day at the Edge of the Water", season="Spring",
epigraph="Be still, and know that I am God.", source="Psalm 46:10",
excerpt="It was cold for the season. The wind came in steady from the water, and there was a kind of brightness to it.",
signed=True, body=[
"It was cold for the season. The wind came in steady from the water, and there was a kind of brightness to it — the sun on the sand, the sound of the surf, all of it sharper than it would have been in summer.",
"We had come to be away. That was the whole point. No list. No schedule. The car in the lot and the long walk down to where the dune grass ends and the beach opens up.",
"A gull flew low across the waves. Then another, picking its way along the tideline. There was no one to watch them but us.",
"I have noticed that the ocean does something to the size of a thing. A worry that felt large in the kitchen looks different from a quarter mile of empty sand. Not gone — never gone — but smaller. Held by something bigger.",
"We did not stay long. The wind was honest about itself. But we stayed long enough.",
"Some days, peace is not something you find. It is something a place gives you, if you go where it lives."]),

dict(no=12, slug="letter-12", title="The City from the Water", season="Spring",
epigraph="What is man, that thou art mindful of him?", source="Psalm 8:4",
excerpt="The boat moves slowly when you are close to the city. There is no hurry once you have arrived where you meant to be.",
signed=True, body=[
"The boat moves slowly when you are close to the city. There is no hurry once you have arrived where you meant to be.",
"Manhattan rises in the distance. From the water, it looks smaller than you expect — a row of buildings on a strip of land, edged by the harbor on both sides. The mind has trouble with it. The city you have walked through, gotten lost in, stood beneath, is the same city now small enough to hold in your eye.",
"She comes into view slowly. Green against the sky, smaller than she ought to be — and somehow, because of that, more herself. I had seen the Statue of Liberty in photographs all my life. Standing on the water, looking at her across the harbor, was something different. Not the picture. The thing the picture was of.",
"The Verrazzano crossed the sky behind us. A bridge so long it seemed to keep going after the eye stopped following it. Boats moved on the surface of the water — small, deliberate, going somewhere.",
"It is strange to be near the largeness of the world and to feel calm in it. I had expected to feel small. I felt held instead.",
"There are places that ask you to be quiet. The water near a great city is one of them."]),

dict(no=13, slug="letter-13", title="The Long Light", season="Summer",
epigraph="Truly the light is sweet, and a pleasant thing it is for the eyes to behold the sun.", source="Ecclesiastes 11:7",
excerpt="It was almost nine last night and still light out. I checked the clock twice because it didn’t seem possible.",
signed=True, body=[
"It was almost nine last night and still light out. I checked the clock twice because it didn’t seem possible.",
"Dinner was over. The dishes were in the sink where I’d left them. I meant to go back in and wash them, but I sat down on the back step instead and never did. The mosquitoes found me around quarter after. I stayed anyway, which is not like me.",
"In January the lights are on by four. You eat dinner, clean the kitchen, and before long the day has packed itself away. I’ve always liked that about winter.",
"Summer lingers.",
"There are all these extra hours, and no instructions for what to do with them.",
"I kept thinking I should get up and do something useful. Pull a few weeds. Pick another cucumber. Tie up the tomatoes one more time.",
"Instead, I stayed where I was.",
"The hummingbirds were still darting between the flowers, just as busy as they’d been all afternoon. The tomatoes looked heavier than they had that morning, the cucumbers seemed to have appeared out of nowhere, and the squash leaves had spread a little farther across the garden. It all looked like it had been growing while I wasn’t paying attention.",
"I spend a lot of time thinking that if I’m sitting still, something must be getting behind.",
"The tomatoes don’t wait for me. Neither do the cucumbers or the squash. They keep growing whether I’m checking on them or not.",
"Eventually I went inside.",
"The dishes were still in the sink.",
"They were still there this morning. It was fine.",
"I’ll probably do the same tonight."]),

dict(no=14, slug="letter-14", title="Cooking Outside", season="Summer",
epigraph=None, source=None,
excerpt="The cedar plank sits in the sink for about an hour before dinner. It always wants to float, so I put a bowl on top of it and leave it alone.",
signed=True, body=[
"The cedar plank sits in the sink for about an hour before dinner. It always wants to float, so I put a bowl on top of it and leave it alone.",
"That’s about all there is to it.",
"By the time the salmon goes on the grill, my part is mostly over. I close the lid and lean against the railing.",
"In the winter I cook facing a wall. The stove is against it, and I spend most evenings looking at the same cabinet doors. I don’t really think about it.",
"Outside is different.",
"From the grill I can see the herbs that need to be picked again. The flowers are full this time of year, and something is always moving through them.",
"There are always animals around here. The finches are everywhere, and every few days a flock of turkeys wanders through the backyard like they’ve been invited. Sometimes they stay awhile. Sometimes they’re gone before dinner is ready.",
"The salmon doesn’t seem to care if I check it every thirty seconds, so I’ve stopped doing that. After a while the cedar starts to smoke just a little, and I smell it before I notice it. That’s usually when I know it’s getting close.",
"Most nights there’s corn. If something’s ready in the garden, that goes on the table too. A cucumber. Fresh basil. Whatever happened to be ready that day.",
"We eat outside because once dinner is ready, it seems like more work to carry everything back into the house."]),

dict(no=15, slug="letter-15", title="Summer by the Sound", season="Summer",
epigraph=None, source=None,
excerpt="The Sound is only a few miles from the house. We don’t really plan to go.",
signed=True, body=[
"The Sound is only a few miles from the house. We don’t really plan to go. One of us will say, “Want to go down to the water?” and before long we’re in the truck.",
"It’s the same place we go in the winter. In February I’m usually wearing a heavy coat with my hands in my pockets, and after twenty minutes I’m ready to head home.",
"This time of year is different.",
"The air smells like salt before you even see the water. Sometimes there’s the smell of flowers mixed in from somebody’s yard along the way. I don’t know why those two smells work together, but they do.",
"Most afternoons you can tell when the rain is coming. The clouds get darker over the water first, and then the wind changes. If you look far enough out, you can usually see the rain before it gets to you.",
"It never stays long.",
"We don’t usually leave anymore. By the time we’d pack everything up and get to the truck, the rain would probably be over.",
"Afterward, everything looks washed clean. The pavement is darker. The air feels cooler.",
"There are still boats out on the Sound. People are walking dogs. Someone’s fishing from the rocks. Every now and then you hear kids laughing farther down the beach, even though you can’t see them.",
"Eventually we head home.",
"The windows stay down the whole way."]),

dict(no=16, slug="letter-16", title="Out Before the Cars", season="Summer",
epigraph=None, source=None,
excerpt="People always talk about how quiet the mornings are. I don’t think they are. The difference isn’t that it’s quiet — it’s that there aren’t many cars yet.",
signed=True, body=[
"I usually leave around seven. Fifteen miles, sometimes twenty, depending on which way I feel like going.",
"The first mile is always the hardest. My legs are stiff, and for a minute I wonder why I thought this sounded like a good idea. It happens every ride.",
"Then it doesn’t.",
"The roads start to open up, and before long I’m passing the same farms I always do. The horses are already outside. I don’t know if they ever sleep late. Most mornings they’re standing along the fence, watching the world wake up.",
"People always talk about how quiet the mornings are.",
"I don’t think they are.",
"The geese have been awake for hours. So have the songbirds. Sometimes a rooster joins in from somewhere I can’t see. The whole ride has a soundtrack if you’re paying attention.",
"The difference isn’t that it’s quiet.",
"It’s that there aren’t many cars yet.",
"Without them, you notice things you usually miss. A screen door closing somewhere down the road. A dog barking behind a barn. The wind moving through the corn. My tires humming over the pavement.",
"Around eight, the morning changes.",
"One car passes. Then another. A school bus pulls out, and someone’s headed to work with a coffee cup in one hand.",
"Before long I’m not alone on the road anymore.",
"I turn toward home.",
"By the time I pull into the driveway, the neighborhood is awake. Garage doors are opening. Somebody’s mowing. A delivery truck rolls past the house.",
"My bike goes back in the garage.",
"I pour another cup of coffee."]),
]
